package thoenluk.aoc2021.challenge16.packet.transpiled;

public class TranspiledPacket5 {
    private static long min(long... args) {
        long min = Long.MAX_VALUE;
        for (long arg : args) {
            min = Math.min(min, arg);
        }
        return min;
    }
    
    private static long max(long... args) {
        long max = Long.MIN_VALUE;
        for (long arg : args) {
            max = Math.max(max, arg);
        }
        return max;
    }
    
    public static long getValue() {
        return (
            62231L
            +
            (
                (
                    (
                        5L
                        +
                        15L
                        +
                        3L
                    )
                    ==
                    (
                        14L
                        +
                        15L
                        +
                        6L
                    )
                ? 1 : 0)
                *
                11060471L
            )
            +
            470L
            +
            max(
                (
                    min(
                        max(
                            (
                                (
                                    (
                                        max(
                                            min(
                                                min(
                                                    max(
                                                        max(
                                                            (
                                                                (
                                                                    min(
                                                                        max(
                                                                            (
                                                                                min(
                                                                                    max(
                                                                                        (
                                                                                            105057548040L
                                                                                        )
                                                                                    )
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
            +
            255024399L
            +
            (
                3317908289L
                *
                (
                    13854500L
                    ==
                    13854500L
                ? 1 : 0)
            )
            +
            (
                549L
                +
                410840L
                +
                70L
                +
                12L
                +
                36731L
            )
            +
            (
                2086L
                *
                (
                    299544L
                    >
                    2748L
                ? 1 : 0)
            )
            +
            max(
                196724896L,
                2749L,
                5L,
                799029L
            )
            +
            (
                108L
                *
                112L
                *
                109L
                *
                62L
                *
                52L
            )
            +
            (
                123L
                *
                151L
                *
                239L
            )
            +
            (
                96L
                *
                125L
            )
            +
            max(
                15L,
                2838L,
                1744L
            )
            +
            (
                (
                    2L
                    +
                    12L
                    +
                    2L
                )
                *
                (
                    14L
                    +
                    9L
                    +
                    6L
                )
                *
                (
                    3L
                    +
                    6L
                    +
                    9L
                )
            )
            +
            (
                (
                    2669L
                    >
                    44956L
                ? 1 : 0)
                *
                832109L
            )
            +
            (
                187255L
            )
            +
            (
                (
                    (
                        4L
                        +
                        8L
                        +
                        11L
                    )
                    >
                    (
                        11L
                        +
                        4L
                        +
                        11L
                    )
                ? 1 : 0)
                *
                3671L
            )
            +
            (
                (
                    229L
                    ==
                    17L
                ? 1 : 0)
                *
                215L
            )
            +
            max(
                272L,
                20L,
                83577913L,
                347L,
                1739L
            )
            +
            (
                (
                    68L
                    <
                    68L
                ? 1 : 0)
                *
                2307L
            )
            +
            9L
            +
            14L
            +
            (
                119L
            )
            +
            (
                4L
                *
                (
                    2L
                    <
                    237L
                ? 1 : 0)
            )
            +
            min(
                15285809L
            )
            +
            (
                34266L
                *
                (
                    77092L
                    >
                    77092L
                ? 1 : 0)
            )
            +
            11L
            +
            (
                (
                    (
                        12L
                        +
                        12L
                        +
                        14L
                    )
                    >
                    (
                        12L
                        +
                        9L
                        +
                        9L
                    )
                ? 1 : 0)
                *
                13L
            )
            +
            (
                (
                    6L
                    *
                    2L
                    *
                    6L
                )
                +
                (
                    15L
                    *
                    9L
                    *
                    11L
                )
                +
                (
                    13L
                    *
                    15L
                    *
                    2L
                )
            )
            +
            (
                (
                    16368768L
                    <
                    84L
                ? 1 : 0)
                *
                8L
            )
            +
            3911L
            +
            (
                2291L
                *
                (
                    666111L
                    <
                    666111L
                ? 1 : 0)
            )
            +
            (
                34L
                *
                117L
                *
                126L
                *
                69L
            )
            +
            (
                151L
                +
                1L
                +
                42393L
            )
            +
            (
                58L
                +
                133721L
                +
                407L
                +
                123L
            )
            +
            max(
                102L,
                4245376655368L
            )
            +
            (
                1210908L
                *
                (
                    44621L
                    <
                    2355497225458L
                ? 1 : 0)
            )
            +
            max(
                518585L
            )
            +
            (
                (
                    877192L
                    >
                    877192L
                ? 1 : 0)
                *
                40132854L
            )
            +
            35160L
            +
            min(
                10L,
                678L
            )
            +
            (
                9894041L
                *
                (
                    (
                        15L
                        +
                        12L
                        +
                        4L
                    )
                    <
                    (
                        9L
                        +
                        14L
                        +
                        3L
                    )
                ? 1 : 0)
            )
            +
            32956L
            +
            (
                (
                    191365059161L
                    >
                    92L
                ? 1 : 0)
                *
                1392L
            )
            +
            min(
                10495L,
                193L,
                3730L
            )
            +
            (
                (
                    (
                        8L
                        +
                        13L
                        +
                        7L
                    )
                    <
                    (
                        9L
                        +
                        13L
                        +
                        9L
                    )
                ? 1 : 0)
                *
                101L
            )
            +
            min(
                6187L,
                2610L,
                25424913L,
                12385L
            )
            +
            (
                214670L
                *
                (
                    48507L
                    >
                    151557L
                ? 1 : 0)
            )
            +
            min(
                2576948864L,
                60047L,
                6L,
                90L,
                3131L
            )
            +
            (
                7L
                +
                1441L
            )
            +
            (
                3828121L
                *
                (
                    238L
                    <
                    3L
                ? 1 : 0)
            )
            +
            76L
            +
            (
                (
                    275L
                    ==
                    1704L
                ? 1 : 0)
                *
                93L
            )
        );
    }
}